export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <html lang="en">
    <body className="bg-white h-full">
      <main className="container mx-auto px-4 sm:px-6 lg:px-8">{children}</main>
    </body>
    // {/* </html> */}
  );
}
