import type { Metadata } from "next";
import { ScrollArea } from "@/components/ui/scroll-area";
import { poppins } from "@/lib/fonts";
import { Toaster } from "@/components/ui/sonner";
import QueryClientProvider from "@/components/QueryClientProvider";
import MobileMenu from "@/components/MobileMenu";
import Link from "next/link";
import Image from "next/image";
import { ChevronDownIcon } from "lucide-react";
import UserMenu from "@/components/UserMenu";
import { getAuthSession } from "@/actions/session";
import logo from "@/../../public/logo.svg";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getAuthSession();

  const fullName = session?.firstName + " " + session?.lastName;
  return (
    // <html lang="en">
    <QueryClientProvider>
      <body className={`${poppins.variable} h-full`}>
        <div className="bg-adminBackground">
          <header className="sticky top-0 z-40 lg:mx-auto lg:px-8">
            <div className="flex h-16 items-center justify-between gap-x-4 border-b border-gray-200 bg-adminBackground px-4 shadow-sm sm:gap-x-6 sm:px-6 lg:px-0 lg:shadow-none">
              <div className="flex gap-x-4 items-center">
                <div>
                  <MobileMenu />
                </div>
                <Link href={"/"} className="lg:ml-12">
                  <Image
                    src={logo}
                    alt="Logo"
                    width={500}
                    height={500}
                    className="w-auto h-6 lg:h-8 object-cover"
                  />
                </Link>
              </div>

              {session?.isLogged ? (
                <UserMenu name={fullName} />
              ) : (
                <Link
                  href="/auth/signin"
                  className="flex items-center gap-x-2 cursor-pointer font-medium"
                >
                  <span>Register / Log in</span>
                  <ChevronDownIcon size={24} />
                </Link>
              )}
            </div>
          </header>
          <main className="">
            <div className="px-8 py-6">
              <ScrollArea className="mx-auto p-4 rounded-2xl bg-white min-h-screen">
                <div className="h-ful p-4">{children}</div>
              </ScrollArea>
            </div>
          </main>
        </div>
        <Toaster richColors position="top-center" />
      </body>
    </QueryClientProvider>
    // </html>
  );
}
