import type { Metadata } from "next";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { poppins } from "@/lib/fonts";
import { Toaster } from "@/components/ui/sonner";
import QueryClientProvider from "@/components/QueryClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    <QueryClientProvider>
      <body className={`${poppins.variable} h-full`}>
        <div className="bg-adminBackground">
          <Header />
          {/* <div className="hidden md:block h-full"> */}
          <Sidebar />
          {/* </div> */}
          <main className="lg:pl-72">
            <div className="px-8 py-6">
              <div className="mx-auto p-4 rounded-2xl bg-white min-h-screen">
                <div className="h-ful p-4">{children}</div>
              </div>
            </div>
          </main>
        </div>
        <Toaster richColors position="top-center" />
      </body>
    </QueryClientProvider>
    // </html>
  );
}
