import type { Metadata } from "next";
import AdminHeader from "@/components/admin-header";
import AdminSidebar from "@/components/admin-sidebar";
import { Toaster } from "@/components/ui/sonner";
import { getAuthSession } from "@/actions/session";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getAuthSession();
  // if (!session) {
  //   return null;
  // }
  // const fullName = session?.firstName + " " + session?.lastName;
  let fullName;
  return (
    <>
      <div className="bg-adminBackground">
        <AdminHeader
          userId={session?.userId || "11231231-asdadsa"}
          userName={fullName || "John Doe"}
          userCredits={1000}
          isAuth={session?.isLogged || false}
        />
        <AdminSidebar
          userId={session?.userId || "11231231-asdadsa"}
          userName={fullName || "John Doe"}
          userCredits={1000}
        />
        <main className="lg:pl-72">
          <div className="px-8 py-6">
            <div className="mx-auto p-4 rounded-2xl bg-white min-h-screen">
              <div className="h-ful p-4">{children}</div>
            </div>
          </div>
        </main>
      </div>
      <Toaster richColors position="top-center" />
    </>
  );
}
